### ISSUE TITLE
Can't locate path: database schema file path

### ISSUE THREAD

**Issue by faizahmedfarooqui** [WebleIT/ZohoBooksLaravelServiceProvider#1]
```
Can't locate path: 
</path/to/project-root/vendor/webleit/zohobookslaravelserviceprovider/src/../database/add_zoho_id_to_users_and_invoices.php>
```

On publishing vendor, I was getting this error. 

Did some digging & found that the actual file name is **2017_12_31_100000_add_zoho_id_to_users_and_invoices.php** in package directory. 

Can you please update the file name to `add_zoho_id_to_users_and_invoices.php` or update the `publishMigrations()` in `ZohoBooksServiceProvider`.

Thanks!

**Comment by Skullbock** [comment]
Sorry for the delayed response, github didn't notify me of the issue
Fixed!
